name: duichai
description: "鍫嗘煷 鈥?浼椾汉鎷炬煷鐏劙楂?
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.4.0
  shared_preferences: ^2.2.0
  flutter_secure_storage: ^9.0.0
  provider: ^6.1.0

  geolocator: ^10.1.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  amap_flutter_map: ^3.0.0

  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  photo_view: ^0.15.0
  image_picker: ^1.0.0
  video_player: ^2.8.0

  intl: ^0.19.0
  url_launcher: ^6.2.0
  share_plus: ^7.2.0
  flutter_svg: ^2.0.0
  permission_handler: ^11.2.0

  in_app_purchase: ^3.1.0

dependency_overrides:
  amap_flutter_map:
    path: ../patched_plugins/amap_flutter_map

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

