name = "duichai-api"
main = "src/index.ts"
compatibility_date = "2026-05-16"
account_id = "c9a49d3635d0fb5508bb79c9069d9f6a"
workers_dev = true

routes = [
  { pattern = "api.duichai.com", custom_domain = true }
]

[[d1_databases]]
binding = "duichai_db"
database_name = "duichai-db"
database_id = "7f14f8d6-4128-42a1-b1ff-57d75b1de622"

[[r2_buckets]]
binding = "duichai_assets"
bucket_name = "duichai-assets"

[vars]
APP_NAME = "堆柴"
ENV = "development"
